spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1091315290047-ulg9e81jfbq6hthbdbo2en2kffcira4m.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile